---
services:
  fedora:
    image: ghcr.io/gunanr/docker-toolbox:fedora
    build: 
      dockerfile: Dockerfile/fedora
      #platforms: [linux/aarch64]
  alpine: 
    image: ghcr.io/gunanr/docker-toolbox:alpine
    build: 
      dockerfile: Dockerfile/alpine
      #platforms: [linux/aarch64]

