---
name: 'Build and Push Docker Containers'

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  alpine:
    name: alpine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: containerfile.alpine
          tags: ghcr.io/${{ github.repository }}:alpine
          push: true
          platforms: linux/amd64,linux/arm64

  fedora:
    name: fedora
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: containerfile.fedora
          tags: ghcr.io/${{ github.repository }}:fedora
          push: true
          platforms: linux/amd64,linux/arm64
